# Generated by Django 5.0.1 on 2024-02-16 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_team_alter_participant_command'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
        migrations.AlterField(
            model_name='participant',
            name='command',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.command'),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
